version: '3.7'

services:
  backend:
      build: .
      command: bash -c "
                python ./manage.py migrate && 
                python ./manage.py runserver 0.0.0.0:8000
              " 
      volumes:
        - ./vaccination:/code
        - .env:/code/.env
      ports:
        - 8000:8000
      links:
        - db

  db:
      image: postgres:11
      ports:
          - 5432:5432
      environment:
          - POSTGRES_PASSWORD=postgres