# Generated by Django 3.2 on 2021-11-12 03:40

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20211112_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.IntegerField(choices=[(1, 'AM10_AM11'), (2, 'AM11_PM12'), (3, 'PM12_PM01'), (4, 'PM01_PM02'), (5, 'PM02_PM03'), (6, 'PM03_PM04'), (7, 'PM04_PM05'), (8, 'PM05_PM06')], default=booking.models.TimeSlotChoices['AM10_AM11']),
        ),
        migrations.AlterField(
            model_name='nurseavailability',
            name='time_slot',
            field=models.IntegerField(choices=[(1, 'AM10_AM11'), (2, 'AM11_PM12'), (3, 'PM12_PM01'), (4, 'PM01_PM02'), (5, 'PM02_PM03'), (6, 'PM03_PM04'), (7, 'PM04_PM05'), (8, 'PM05_PM06')], default=booking.models.TimeSlotChoices['AM10_AM11']),
        ),
    ]
