# Generated by Django 3.2 on 2021-11-12 03:44

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20211112_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '10:00 - 11:00'), (2, '11:00 - 12:00'), (3, '12:00 - 13:00'), (4, '13:00 - 14:00'), (5, '14:00 - 15:00'), (6, '15:00 - 16:00'), (7, '16:00 - 17:00'), (8, '17:00 - 18:00')], default=booking.models.TimeSlotChoices['AM10_AM11']),
        ),
        migrations.AlterField(
            model_name='nurseavailability',
            name='time_slot',
            field=models.IntegerField(choices=[(1, '10:00 - 11:00'), (2, '11:00 - 12:00'), (3, '12:00 - 13:00'), (4, '13:00 - 14:00'), (5, '14:00 - 15:00'), (6, '15:00 - 16:00'), (7, '16:00 - 17:00'), (8, '17:00 - 18:00')], default=booking.models.TimeSlotChoices['AM10_AM11']),
        ),
    ]
